services:
  nginx:
    image: nginx:1.25.5-alpine-slim
    ports:
      - 8000:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
  auth:
    image: ghcr.io/hackathon-m1-al/authentification:v0.0.2
    ports:
      - 8001:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - postgres
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: testdb
    ports:
      - 5432:5432
  api-crud:
    image: ghcr.io/hackathon-m1-al/api-crud:v0.0.0
    environment:
        - SPRING_DATASOURCE_URL=jdbc:mysql://api-crud-database:3306/hackathon_api
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - api-crud-database
  api-crud-database:
    image: mysql:8.3
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: hackathon_api
